<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <LangVersion>latestmajor</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GodotSharp.SourceGenerators" Version="2.7.0-251124-0938.Release" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="SmartFormat" Version="3.6.1" />
    <PackageReference Include="SpotifyAPI.Web" Version="7.2.1" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
    <PackageReference Include="Tmds.DBus" Version="0.23.0" />
  </ItemGroup>
</Project>